# Generated by Django 5.2.12 on 2026-03-19 16:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='物语标题')),
                ('total_seats', models.IntegerField(verbose_name='席位数')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='基础单价')),
                ('discount', models.IntegerField(default=100, verbose_name='折扣(%)')),
                ('description', models.TextField(verbose_name='前情提要')),
                ('status', models.CharField(choices=[('open', '销售中'), ('unboxed', '已开箱')], default='open', max_length=20, verbose_name='运作状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '发售车队',
                'verbose_name_plural': '发售车队(商品箱)',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='中介门脸名')),
                ('address', models.TextField(verbose_name='坐落位置')),
                ('hours', models.CharField(default='10:00 - 22:00', max_length=100, verbose_name='魔法交汇时间(营业时间)')),
            ],
            options={
                'verbose_name': '自提次元据点',
                'verbose_name_plural': '系统预设线下据点',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('balance', models.DecimalField(decimal_places=2, default=5000.0, max_digits=12, verbose_name='金币能量')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '勇者',
                'verbose_name_plural': '勇者(用户)',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='接收人代号')),
                ('phone', models.CharField(max_length=50, verbose_name='联络信号')),
                ('detail', models.TextField(verbose_name='详细物理坐标')),
                ('is_default', models.BooleanField(default=False, verbose_name='设为首选着陆点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '坐标字典',
                'verbose_name_plural': '勇者坐标地址',
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, verbose_name='赏级体系(如 SP/A/B)')),
                ('name', models.CharField(max_length=200, verbose_name='奖项名称')),
                ('count', models.IntegerField(verbose_name='原始配置数量')),
                ('img', models.URLField(blank=True, max_length=500, null=True, verbose_name='展示模型URL')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='app.activecar', verbose_name='所属车队')),
            ],
            options={
                'verbose_name': '配置奖项',
                'verbose_name_plural': '箱体内奖项池',
            },
        ),
        migrations.CreateModel(
            name='ItemRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(verbose_name='当期摇中座次')),
                ('status', models.CharField(choices=[('in_warehouse', '虚空中保留'), ('shipping', '打包快递中'), ('shipped', '已完成传送')], default='in_warehouse', max_length=20, verbose_name='当前存留状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.activecar', verbose_name='出处车队')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prize', verbose_name='掉落原奖项')),
            ],
            options={
                'verbose_name': '稀有战利品',
                'verbose_name_plural': '个人仓库掉落实况',
            },
        ),
        migrations.CreateModel(
            name='ShippingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='express', max_length=20, verbose_name='传送承制方')),
                ('status', models.CharField(default='打包中', max_length=20, verbose_name='物流跟踪态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请创建刻度')),
                ('items', models.ManyToManyField(related_name='shipping_orders', to='app.itemrecord', verbose_name='被打包的单品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '传送履历归档',
                'verbose_name_plural': '物流传送发货总表',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(verbose_name='座位号码')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='app.activecar', verbose_name='所属车队')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='占坑勇者')),
            ],
            options={
                'verbose_name': '排号席位',
                'verbose_name_plural': '实时选座概况',
                'unique_together': {('car', 'seat_number')},
            },
        ),
    ]
