# Generated by Django 5.2.12 on 2026-03-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingrecord',
            name='receiver_info',
            field=models.TextField(blank=True, null=True, verbose_name='收件/自提详情'),
        ),
    ]
