# Generated by Django 5.2.12 on 2026-03-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shippingrecord_receiver_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activecar',
            options={'ordering': ['-order', '-created_at'], 'verbose_name': '发售车队', 'verbose_name_plural': '发售车队(商品箱)'},
        ),
        migrations.AddField(
            model_name='activecar',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序权重(大者靠前)'),
        ),
        migrations.AddField(
            model_name='shippingrecord',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='自提验证码'),
        ),
    ]
