# Generated by Django 5.2.12 on 2026-03-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_activecar_options_activecar_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingrecord',
            name='courier_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='快递公司'),
        ),
        migrations.AddField(
            model_name='shippingrecord',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='快递单号'),
        ),
    ]
