# Generated by Django 5.2.12 on 2026-03-20 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_shippingrecord_courier_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='快递公司名称')),
            ],
            options={
                'verbose_name': '快递字典',
                'verbose_name_plural': '快递公司字典',
            },
        ),
        migrations.RemoveField(
            model_name='shippingrecord',
            name='courier_name',
        ),
        migrations.AddField(
            model_name='shippingrecord',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='物流资费(元)'),
        ),
        migrations.AddField(
            model_name='shippingrecord',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.expresscompany', verbose_name='承运商'),
        ),
    ]
