# Generated by Django 5.2.12 on 2026-03-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_expresscompany_remove_shippingrecord_courier_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingrecord',
            name='method',
            field=models.CharField(choices=[('express', '快递'), ('pickup', '自提')], default='express', max_length=20, verbose_name='发货方式'),
        ),
        migrations.AlterField(
            model_name='shippingrecord',
            name='receiver_info',
            field=models.TextField(blank=True, null=True, verbose_name='发货地址/据点详情'),
        ),
        migrations.AlterField(
            model_name='shippingrecord',
            name='status',
            field=models.CharField(choices=[('打包中', '打包中'), ('运输中', '运输中'), ('待自提', '待自提'), ('已达成', '已达成'), ('奖励交付', '奖励交付')], default='打包中', max_length=20, verbose_name='物流状态'),
        ),
    ]
